### ISSUE TITLE
Do we need Makie as dependency?

### ISSUE THREAD

**Issue by alanderos91** [LangeSymposium/2022-July-Workshop#9]
I'm using GLMakie for a very brief visualization. The Dockerfile has Makie, but this does not seem to make any of the backends available. See the screenshot. I think we only need to specify a backend like GLMakie or CairoMakie? I can use whichever is available for the other sections.

![Screenshot_2022-07-15_19-09-07](https://user-images.githubusercontent.com/25474284/179336465-f0367d60-eb0c-4773-96c6-d34b1aa42006.png)

**Comment by kose-y** [comment]
I added GLMakie for now. We are using the docker image under Hua's account on Docker Hub, so I think we need to wait for him to rebuild the image. @Hua-Zhou

**Comment by Hua-Zhou** [comment]
Thanks @kose-y 

Do you have a Docker ID? I can add you as a collaborator of <https://hub.docker.com/repository/docker/huazhou/lange_symposium_workshop_2022> So you can build Docker image locally and then push to this Docker repo.

**Comment by kose-y** [comment]
@Hua-Zhou It is `kose`.

**Comment by Hua-Zhou** [comment]
@alanderos91 

Instead of GLMakie.jl, you may use CairoMakie.jl, which is already in the current Docker image.

**Comment by Hua-Zhou** [comment]
> @Hua-Zhou It is `kose`.

Just added you as a collaborator.

**Comment by alanderos91** [comment]
Yes, I’ll switch the backend.
